# Generated by Django 2.1 on 2018-08-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0003_result_apppk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmodel',
            name='cover',
            field=models.URLField(default='https://i.imgur.com/5lH7xkG.jpg'),
        ),
    ]
