# Generated by Django 2.1 on 2018-08-16 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fbapp', '0004_auto_20180814_2104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appmodel',
            options={'ordering': ['-pk']},
        ),
    ]
